infoholic/urls.py
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^microblog/', include('microblog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        
    url(r'^signup/$', 'infoholic.views.register', name='signup'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'infoholic/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'infoholic/index.html'}, name='logout'),

    url(r'^$', views.HomepageView.as_view(), name='home'),                   
    url(r'^default/$', 'infoholic.views.user_default', name='user_default'),                   
    url(r'^category/(?P<slug>[\w-]+)/$', 'infoholic.views.category_detail',
        name='category_detail'),
    url(r'^category/(?P<slug1>[\w-]+)/(?P<slug2>[\w-]+)/$',
        'infoholic.views.feed_detail', name='feed_detail'),
                       
    url(r'^userprofile/$', 'infoholic.views.user_profile', name='user_profile'),
    url(r'^editsource/$', 'infoholic.views.edit_source', name='edit_source'),
    #url(r'^(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='detail'),
)

my1stsite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from . import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my1stsite.views.home', name='home'),
    # url(r'^my1stsite/', include('my1stsite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomepageView.as_view(), name='home'),
    url(r'^infoholic/', include('infoholic.urls', namespace='infoholic')),
)

urlpatterns += patterns('',
    (r'^static/(.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT
    }),
)

infoholic/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class TimeStampedModel(models.Model):
    '''
    An abstract base class model that provides self-updating
    "created_at" and "updated_at" fields.
    '''
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True


class Category(TimeStampedModel):
    """
    category of articles, such as News, Business etc
    """
    name = models.CharField(max_length=255)
    slug_name = models.SlugField(max_length=255, blank=True, default='')
    owners = models.ManyToManyField(User, related_name='categories')
    
    class Meta:
        ordering = ["created_at", "name"]

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug_name:
            self.slug_name = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Feed(TimeStampedModel):
    """
    an RSS feed
    """
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255) #ex, http://www.theverge.com/rss/index.xml
    slug = models.SlugField(max_length=255, blank=True, default='')
    owners = models.ManyToManyField(User, related_name='feeds')
    category = models.ForeignKey(Category)
    
    class Meta:
        ordering = ["created_at", "title"]

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Feed, self).save(*args, **kwargs)


class Article(models.Model):
    """
    articles parsed from an RSS feed
    """
    fetched_at = models.DateTimeField(auto_now_add=True, editable=False)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    readed = models.BooleanField(default=False)
    link = models.CharField(max_length=255, blank=True, default='')
    reader = models.ForeignKey(User, related_name="articles")
    source = models.ForeignKey(Feed, related_name="articles") #feed 
    category = models.ForeignKey(Category, related_name="articles") #category 
    
    class Meta:
        ordering = ["-fetched_at", "title"]

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.link)
        super(Article, self).save(*args, **kwargs)

    

infoholic/views.py
from django.views.generic import TemplateView
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.hashers import check_password
from django.template.defaultfilters import slugify

from .models import Article, Category, Feed
from .tasks import fetch_article, start_worker

from feedparser import parse


class HomepageView(TemplateView):
    template_name = 'infoholic/index.html'


def register(request):
    """
    to register a new user
    """
    if request.method == 'POST':
        new_user = User()
        new_user.username = request.POST['username']
        new_user.email = request.POST['email']
        new_user.set_password(request.POST['password'])
        new_user.save()

        #assign guest's categories, feeds and some articles to this mew user
        user_guest = User.objects.get(username='guest')
        for category in user_guest.categories.all():
            category.owners.add(new_user)
            for feed in user_guest.feeds.filter(category=category):
                feed.owners.add(new_user)
                for article in user_guest.articles.filter(category=category, source=feed).order_by('-fetched_at')[:4]:
                    default_article = Article()
                    default_article.title = article.title
                    default_article.source = article.source
                    default_article.category = article.category
                    default_article.content = article.content
                    default_article.link = article.link
                    default_article.reader = new_user
                    default_article.save()


        #manually log new_user in
        username = request.POST.get('username', '')
        password = request.POST['password']
        user = authenticate(username=new_user.username,
                            password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('infoholic:user_default'))
        else:
            return HttpResponseRedirect(reverse('infoholic:signup'))
      
    else:
        return HttpResponseRedirect(reverse('infoholic:home'))


def user_profile(request):
    """
    to edit user's user's profile
    """
    if request.user.is_authenticated():
        template_name = "infoholic/user_profile.html"
        if request.method == 'POST':
            if request.POST['newEmail'] is not None:
                request.user.email = request.POST['newEmail']
                request.user.save()
            if check_password(request.POST['currentPassword'], request.user.password):
                if (request.POST['newPassword'] is not None) and \
                   (request.POST['confirmPassword'] is not None) and \
                   (request.POST['newPassword'] == request.POST['confirmPassword']):
                    request.user.set_password(request.POST['newPassword'])
                    request.user.save()
                                    
            return HttpResponseRedirect(reverse('infoholic:user_default'))
        else:
            return render(request, template_name)
    else:
        return HttpResponseRedirect(reverse('infoholic:home'))

            
def edit_source(request):
    """
    to add new category and feed for current user
    """
    template_name = "infoholic/edit_source.html"
    if request.method == 'POST':
        if request.POST['new_cat_name'] != '':
            new_cat_added = False #new category already in db?
            new_category = Category(name=request.POST['new_cat_name'])
            for category in Category.objects.all():
                if category.name == new_category.name:
                    if category not in request.user.categories.all():
                        category.owners.add(request.user)
                    new_cat_added = True
                        
            if not new_cat_added:
                new_category.save()
                new_category.owners.add(request.user)
                
        if request.POST['new_feed_title'] != '':
            assigned_category = request.user.categories.get(
                    name=request.POST['new_feed_cat'])
            new_feed = Feed(title=request.POST['new_feed_title'],
                                category=assigned_category,
                                link=request.POST['new_feed_link'])
            new_feed_added = False
            for feed in Feed.objects.all():
                #actually use feed.link to differentiate feeds
                if feed.link == new_feed.link:
                    if feed not in request.user.feeds.all():
                        feed.owners.add(request.user)
                    new_feed_added = True
                        
            if not new_feed_added:
                new_feed.save()
                new_feed.owners.add(request.user)
            
        return HttpResponseRedirect(reverse('infoholic:user_default'))
    else:
        return render(request, template_name)


def user_default(request):
    """
    the landing page for a logged in user
    """
    start_worker() #wake up worker for future article parsing

    template_name = "infoholic/read_article.html"
    if request.user.is_authenticated():
        user = request.user        
    else:
        user = User.objects.get(username='guest')
    username = user.username
    category_list = user.categories.all().order_by('created_at')
    default_cat = category_list[0] 
    feed_list = user.feeds.filter(category=default_cat).order_by(
                'created_at')
    default_feed = feed_list[0] 

    fetch_article.delay(user, default_cat, default_feed) #issue a task to parse new articles
        
    article_list = user.articles.filter(category=default_cat,
                                    source=default_feed)[:10]

    context = {
        'username'     : username,
        'category_list': category_list,
        'cat_selected'  : default_cat,
        'feed_list'    : feed_list,
        'feed_selected' : default_feed,
        'article_list' : article_list
    }
    return render(request, template_name, context)


def category_detail(request, slug):
    """
    to display articles of a certain category
    """
    template_name = "infoholic/read_article.html"
    if request.user.is_authenticated():
        user = request.user        
    else:
        user = User.objects.get(username='guest')
    username = user.username
    category_list = user.categories.all().order_by('created_at')
    cat_selected = user.categories.get(slug_name=slug)
    feed_list = user.feeds.filter(category=cat_selected).order_by(
                'created_at')

    article_titles = []
    for article in user.articles.all():
        article_titles.append(article.title)

    for feed in feed_list:
        fetch_article.delay(user, cat_selected, feed) #to parse articles
               
    article_list = user.articles.filter(category=cat_selected)
    context = {
        'username'      : username,
        'category_list' : category_list,
        'cat_selected'  : cat_selected,
        'feed_list'     : feed_list,
        'article_list'  : article_list
    }
    return render(request, template_name, context)


def feed_detail(request, slug1, slug2):
    """
    to display articles of a certain feed
    """
    template_name = "infoholic/read_article.html"
    if request.user.is_authenticated():
        user = request.user        
    else:
        user = User.objects.get(username='guest')
    username = user.username
    category_list = user.categories.all().order_by('created_at')
    cat_selected = user.categories.get(slug_name=slug1)
    feed_list = user.feeds.filter(category=cat_selected).order_by(
                'created_at')
    feed_selected = user.feeds.get(slug=slug2)
    
    fetch_article.delay(user, cat_selected, feed_selected)
    
    '''            
    #temporary measurement to control the amount of articles of
    #a certain feed
    num_feed_articles = user.articles.filter(category=cat_selected,
                                    source=feed_selected).count()
    if num_feed_articles > parse_len:
        for j in range(num_feed_articles-1, parse_len+9, -1):
            user.articles.filter(category=cat_selected,
                                 source=feed_selected)[j].delete()
    '''
        
    article_list = user.articles.filter(category=cat_selected,
                                    source=feed_selected)
    
    context = {
        'username'     : username,
        'category_list': category_list,
        'cat_selected' : cat_selected,
        'feed_list'    : feed_list,
        'feed_selected': feed_selected,
        'article_list' : article_list
    }
    return render(request, template_name, context)   

infoholic/templates/infoholic/category_detail.html
{% extends "_layouts/base.html" %}

{% block page_title %} The Infoholic | {% endblock %}

{% block page_content %}
<style type="text/css">
	
</style>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!--<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>-->
          <!--<a class="brand" href="#"><img src="{{ STATIC_URL }}img/w3r.png" width="111" height="30" alt="w3resource logo" /></a> 
          	-->
          <a class="brand">The Infoholic</a>-->
          <div class="nav-collapse">
            <ul class="nav">
              
              <li class="active"><a href="{% url 'infoholic:user_default' %}">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <!-- <p class="navbar-text pull-right">Hello, <a href="#">{{ username }}</a></p> -->
            <div class="btn-group pull-right">
		    	<a class="btn btn-primary"><i class="icon-user icon-white"></i>{{ username }}</a>
		    	<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
		    	<ul class="dropdown-menu">
		    		<li><a href="{% url 'infoholic:user_profile' %}" ><i class="icon-pencil"></i> Edit</a></li>
		    		<li><a href="{% url 'infoholic:logout' %}"><i class="icon-home"></i> Log out</a></li>
		      	</ul>
		    </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- navbar -->
    
    
    <!--<div class="container"> -->
    <div class="container-fluid">
	  
      <div class="span2">
	    <div class="SidebarContainer" >
	      <div class="well sidebar-nav" data-spy="affix" data-offset-top="200">
	        <ul class="nav nav-list">
	        
	        	{% for category in category_list %}
	        		{% if category == cat_selected %}
	        			<li class="sidebar-list active"><a href="{% url 'infoholic:category_detail' category.name %}"><h4>{{ category.name }}</h4></a></li>
	        			{% for feed in feed_list %}
	        		 		<div class="sidebar-list-detail"><a href="{% url 'infoholic:feed_detail' category.slug_name feed.slug %}"><h5>{{ feed.title }}</h5></a></div>
	        		 	{% endfor %}
	        		{% else %}
	        			<li class="sidebar-list"><a href="{% url 'infoholic:category_detail' category.name %}"><h4>{{ category.name }}</h4></a></li>
	        		{% endif %}
	        	{% endfor %}
	        	<hr>      
	        	<li class="sidebar-list"><a href="{% url 'infoholic:edit_source' %}"><h4><em>More...</em></h4></a></li>                         
	        
	        </ul>
	      </div><!--/.well -->
	    </div><!--/sidebarContainer-->
	  </div><!--/span-->
	  
	  
    
	  <div class="span9">
	    <!--
	    <div class="container-fluid">
	      <h2>Knowledge is power.</h1>
	    </div>
	    -->
	    <div class="container">
	        {% for article in article_list %}
				<div class="span9">
					<div>
	              		<h3><li><a href="{{ article.link }}">{{ article.title }}</a></li></h3>
	              	</div>
	              	<div>
	              		{% autoescape off %}{{ article.content }}{% endautoescape %}
	             	</div>
	              	<div>
	              		<p><a class="btn " href="{{ article.link }}">{{ article.source }}</a></p>
	              	</div>
	            </div><!--/span-->
			{% empty %}
				<div class="span9"><h2>Sorry, no article yet. Check back soon!</h2></div>
			{% endfor %}
	    </div><!--/container-->
	    
	  </div><!--/span--> 
	
	</div><!--/.fluid-container-->
	<footer>
		<p>&copy; ZZZ 2013</p>
	</footer>
	<!--</div>-->
{% endblock %}

infoholic/templates/infoholic/login.html
{% extends "_layouts/base.html" %}

{% block page_content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'infoholic:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Submit" />
<input type="hidden" name="next" value="{% url 'infoholic:user_default' %}" />
</form>

{% endblock %}

infoholic/templates/infoholic/post_detail.html

{% extends "_layouts/base.html" %}
{% load url from future %}
{% block page_title %}{{ post.title }} | {% endblock %}

{% block page_content %}
<h2>{{ post.title }}</h2>
{{ post.content|linebreaks }}

<p>{{ post.updated_at }}</p>
<p><a href="{% url 'blog:list' %}">&larr; Blog List</a></p>
{% endblock %}	

infoholic/templates/infoholic/read_article.html
{% extends "_layouts/base.html" %}

{% block page_title %} Infoholic | {% endblock %}

{% block page_content %}
<style type="text/css">
	#content-background {
		position: fixed;
		top: -50%;
		left: -50%;
		width: 200%;
		height: 200%;
		z-index: -999999;
	}
	#content-background img {
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		margin: auto;
		min-width: 50%;
		min-height: 50%;
	}
</style>
<!--
<div id="content-background" >
	<img src="{{ STATIC_URL }}img/P1030889-2.jpg">
</div>
-->
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!--<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>-->
          <!--<a class="brand" href="#"><img src="{{ STATIC_URL }}img/w3r.png" width="111" height="30" alt="w3resource logo" /></a>
          	-->
          <a class="brand">The Infoholic</a>-->
          <div class="nav-collapse">
            <ul class="nav">

              <li><a href="{% url 'infoholic:user_default' %}">Home</a></li>
              <li><a href="#aboutModal" data-toggle="modal">About</a></li>
              <li><a href="mailto:greenmoonshisu@gmail.com">Contact</a></li>
            </ul>
            <ul class="nav">
            	<form class="form-search">
            		<div class="input-append">
    	  				<input type="text" class="span2 search-query" placeholder="under construction!">
    	  				<button type="submit" class="btn" disabled>Search</button>
    	  			</div>
    	  		</form>
            </ul>
            <!-- <p class="navbar-text pull-right">Hello, <a href="#">{{ username }}</a></p> -->
            <div class="btn-group pull-right">
		    	<a class="btn btn-primary"><i class="icon-user icon-white"></i>{{ username }}</a>
		    	<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
		    	<ul class="dropdown-menu">
		    		{% if username == 'guest' %}
		    			<li><a href="{% url 'infoholic:logout' %}"><i class="icon-home"></i> Bye bye</a></li>
		    		{% else %}
		    			<li><a href="{% url 'infoholic:user_profile' %}"><i class="icon-pencil"></i> Edit</a></li>
		    			<li><a href="{% url 'infoholic:logout' %}"><i class="icon-home"></i> Log out</a></li>
		    		{% endif %}
		      	</ul>
		    </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- navbar -->


    <!--<div class="container"> -->
    <div class="container-fluid">

      <div class="span2">
	    <div class="SidebarContainer" >
	      <div class="well sidebar-nav" data-spy="affix" data-offset-top="200">
	        <ul class="nav nav-list">

	        	{% for category in category_list %}
	        		{% if category == cat_selected %}
	        			{% if feed_selected == None %}
	        				<li class="sidebar-list active"><a href="{% url 'infoholic:category_detail' category.slug_name %}"><h4>{{ category.name }}</h4></a></li>
	        			{% else %}
	        				<li class="sidebar-list"><a href="{% url 'infoholic:category_detail' category.slug_name %}"><h4>{{ category.name }}</h4></a></li>
	        			{% endif %}
	        			{% for feed in feed_list %}
	        				{% if feed == feed_selected %}
	        					<li class="sidebar-list-detail active"><a href="{% url 'infoholic:feed_detail' category.slug_name feed.slug %}"><h6>{{ feed.title }}</h6></a></li>
	        		 		{% else %}
	        		 			<li class="sidebar-list-detail"><a href="{% url 'infoholic:feed_detail' category.slug_name feed.slug %}"><h6>{{ feed.title }}</h6></a></li>
	        		 		{% endif %}
	        		 	{% endfor %}
	        		{% else %}
	        			<li class="sidebar-list"><a href="{% url 'infoholic:category_detail' category.slug_name %}"><h4>{{ category.name }}</h4></a></li>
	        		{% endif %}
	        	{% endfor %}
	        	<hr>
	        	{% if username != 'guest' %}
	        		<li class="sidebar-list"><a href="{% url 'infoholic:edit_source' %}"><h4><em>More...</em></h4></a></li>
	        	{% endif %}
	        </ul>
	      </div><!--/.well -->
	    </div><!--/sidebarContainer-->
	  </div><!--/span-->

	  <div class="span9">

	    <div class="container-fluid" >
	 	<!--   	<div class="search-field" data-spy="affix" data-offset-top="200">


	      		<h2>This field is gonna be replaced with search</h1>
	      		</div>-->

	    </div>

	    <div class="container">
	        {% for article in article_list %}
				<div class="span9">
					<div>
	              		<h3><li><a href="{{ article.link }}">{{ article.title }}</a></li></h3>
	              	</div>
	              	<div>
	              		{% autoescape off %}{{ article.content }}{% endautoescape %}
	             	</div>
	              	<div>
	              		<p><a class="btn " href="{{ article.link }}">{{ article.source }}</a></p>
	              	</div>
	            </div><!--/span-->
			{% empty %}
				<div class="span9"><h2>Sorry, no articles yet. Coming soon!</h2></div>
			{% endfor %}
	    </div><!--/container-->

	  </div><!--/span-->

	</div><!--/.fluid-container-->
	<footer>
		<p>&copy; Zoie Cheng 2013</p>
	</footer>
	<!--</div>-->

	<div id="aboutModal" class="modal hide fade">
    	<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    		<h3>About this site</h3>
    	</div>
    	<div class="modal-body">
    		<p>This RSS reader was initially created to practice and showcase what I have learned about web development.
    		   Although it was obviously for personal usage, I still tried to make it as complete as a business project.
    		</p>
    		<p class="text-right">
    			<a href="mailto:greenmoonshisu@gmail.com">
    				<em>Zoie </em>
    			</a>

    		</p>
    		<p class="text-right">Apr. 2013</p>
    	</div>
    	<div class="modal-footer">
    		<a href="" class="btn btn-primary">Close</a>
    	</div>
    </div>
{% endblock %}

infoholic/templates/infoholic/register.html
{% extends "_layouts/base.html" %}

{% block page_title %}Create an account{% endblock %}

{% block page_content %}
  <h1>Create an account</h1>

  <form action="" method="post">
  {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create the account">
  </form>
{% endblock %}

infoholic/templates/infoholic/user_default.html
{% extends "_layouts/base.html" %}

{% block page_title %}Infoholic | {% endblock %}

{% block page_content %}

	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!--<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>-->
          <!--<a class="brand" href="#"><img src="{{ STATIC_URL }}img/w3r.png" width="111" height="30" alt="w3resource logo" /></a>
          	-->
          <a class="brand">The Infoholic</a>-->
          <div class="nav-collapse">
            <ul class="nav">

              <li class="active"><a href="{% url 'infoholic:user_default' %}">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <!-- <p class="navbar-text pull-right">Hello, <a href="#">{{ user.username }}</a></p> -->
            <div class="btn-group pull-right">
		    	<a class="btn btn-primary"><i class="icon-user icon-white"></i>{{ username }}</a>
		    	<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
		    	<ul class="dropdown-menu">
		    		<li><a href="{% url 'infoholic:user_profile' %}"><i class="icon-pencil"></i> Edit</a></li>
		    		<li><a href="{% url 'infoholic:logout' %}"><i class="icon-home"></i> Log out</a></li>
		      	</ul>
		    </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- navbar -->


    <!--<div class="container"> -->
    <div class="container-fluid">

      <div class="span2">
	    <div class="SidebarContainer" >
	      <div class="well sidebar-nav" data-spy="affix" data-offset-top="200">
	        <ul class="nav nav-list">

	        	{% for category in category_list %}
	        		{% if category == cat_selected %}
	        			<li class="sidebar-list active"><a href="{% url 'infoholic:category_detail' category.name %}"><h4>{{ category.name }}</h4></a></li>
	        			{% for feed in feed_list %}
	        		 		<div class="sidebar-list-detail"><a href="{% url 'infoholic:feed_detail' category.slug_name feed.slug %}"><h5>{{ feed.title }}</h5></a></div>
	        		 	{% endfor %}
	        		{% else %}
	        			<li class="sidebar-list"><a href="{% url 'infoholic:category_detail' category.name %}"><h4>{{ category.name }}</h4></a></li>
	        		{% endif %}
	        	{% endfor %}
	        	<hr>
	        	<li class="sidebar-list"><a href="{% url 'infoholic:edit_source' %}"><h4><em>More...</em></h4></a></li>

	        </ul>
	      </div><!--/.well -->
	    </div><!--/sidebarContainer-->
	  </div><!--/span-->

	  <div class="span9">
	    <!--
	    <div class="container-fluid">
	      <h2>Knowledge is power.</h1>
	    </div>
	    -->
	    <div class="container">
	        {% for article in article_list %}
				<div class="span9">
					<div>
	              		<h3><li><a href="{{ article.link }}">{{ article.title }}</a></li></h3>
	              	</div>
	              	<div>
	              		{% autoescape off %}{{ article.content }}{% endautoescape %}
	             	</div>
	              	<div>
	              		<p><a class="btn " href="{{ article.link }}">{{ article.source }}</a></p>
	              	</div>
	            </div><!--/span-->
			{% empty %}
				<div class="span9"><h2>Sorry, no article yet. Check back soon!</h2></div>
			{% endfor %}
	    </div><!--/container-->

	  </div><!--/span-->

	</div><!--/.fluid-container-->
	<footer>
		<p>&copy; ZZZ 2013</p>
	</footer>
	<!--</div>-->
{% endblock %}